import type { Metadata } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import StoreProvider from './StoreProvider';
import ToastProvider from '@/provider/ToastProvider';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { baseLightTheme } from '@/utils/theme/DefaultColors';
import { DialogProvider } from '../context/DialogContext'; // Import the DialogProvider


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={baseLightTheme}>
            <CssBaseline />
            <StoreProvider>
            <DialogProvider>
              <ToastProvider>{children}</ToastProvider>
            </DialogProvider>
            </StoreProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
